### ISSUE TITLE
This is a copy-paste of Go stdlib and claims Facebook copyright

### ISSUE THREAD

**Issue by tv42** [facebookgo/structtag#1]
This is copy-pasted from Go stdlib with just the error return added, and claims Facebook copyright etc. The code has been part of since before go1. Wtf?

https://github.com/golang/go/commit/25733a94fde4f4af4b6ac5ba01b7212a3ef0f013#diff-fea606da31d91b5dd55e1029dc8b1c00R719

**Comment by daaku** [comment]
Oh yeah, totally my error. Will fix it right away.
